Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M:%S'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M:%S'
Time::DATE_FORMATS[:date] = '%Y/%m/%d'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:utc_datetime] = '%Y-%m-%dT%H:%M:%S'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'
